from enum import StrEnum


class JobEventType(StrEnum):
    CREATED = "CREATED"
    CLAIMED = "CLAIMED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_SUCCEEDED = "EXECUTION_SUCCEEDED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    RECOVERED = "RECOVERED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"